apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: process-exporter
    app.kubernetes.io/name: process-exporter
    app.kubernetes.io/version: v1.0.1
  name: process-exporter
  namespace: openshift-monitoring
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9256
    protocol: TCP
    targetPort: 9256
  selector:
    app.kubernetes.io/name: process-exporter
  sessionAffinity: None
  type: ClusterIP
