apiVersion: v1
kind: ConfigMap
metadata:
  name: process-exporter
  namespace: openshift-monitoring
data:
  config.yml: |
    process_names:
      - comm:
        - systemd
        cmdline:
        - --system
      - ppid: 1
